### PR TITLE
Curate cipherlist based on Mozilla Old configuration

### PR DESCRIPTION
**Pull request by dharmab**
Curate the Envoy TLS ciphers to balance security and compatibility. See updated code comment for cipher selection methodology.

### CODE REVIEW

**Comment by phylake** [comment]
@dharmab did you test this?

**Comment by phylake** [comment]
@dharmab also needs an `ADOBE_CHANGELOG.md` update

**Comment by dharmab** [comment]
No, @lrouquette was going to help me there.

Adobe changlog update will conflict with #9, so waiting for that merge

**Comment by phylake** [comment]
#9 is merged

**Comment by dharmab** [comment]
Rebased and updated changelog.

**Comment by phylake** [comment]
Lmk when the testing is complete

**Comment by dharmab** [comment]
Closing as @lrouquette was able to determine that Envoy doesn't actually support old ciphers! 😂 

https://github.com/envoyproxy/envoy/issues/8848#issuecomment-548672667

**Pull request closed without merging**
